gui:
  create:
    title: "§aСоздание рецепта: {id}"
    background:
      material: GRAY_STAINED_GLASS_PANE
      name: " "
    save-slot: 48
    save-name: "§aСохранить"
    cancel-slot: 50
    cancel-name: "§cОтмена"
    result-slot: 24  # Центральный правый слот (результат)

  list:
    title: "§eСписок рецептов — страница {page}"
    size: 54
    background:
      material: BLACK_STAINED_GLASS_PANE
      name: " "

messages:
  saved: "§aРецепт '{id}' успешно сохранён!"
  cancelled: "§cСоздание рецепта отменено."
  removed: "§cРецепт '{id}' удалён!"
  not-found: "§cРецепт '{id}' не найден."
